# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/brotter/anita16/anitaBuildTool/components/UCorrelator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/brotter/anita16/anitaBuildTool/components/UCorrelator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brotter/anita16/anitaBuildTool/components/UCorrelator/CMakeFiles /Users/brotter/anita16/anitaBuildTool/components/UCorrelator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/brotter/anita16/anitaBuildTool/components/UCorrelator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doAll

# Build rule for target.
doAll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doAll
.PHONY : doAll

# fast build rule for target.
doAll/fast:
	$(MAKE) -f CMakeFiles/doAll.dir/build.make CMakeFiles/doAll.dir/build
.PHONY : doAll/fast

#=============================================================================
# Target rules for targets named doSimulated

# Build rule for target.
doSimulated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doSimulated
.PHONY : doSimulated

# fast build rule for target.
doSimulated/fast:
	$(MAKE) -f CMakeFiles/doSimulated.dir/build.make CMakeFiles/doSimulated.dir/build
.PHONY : doSimulated/fast

#=============================================================================
# Target rules for targets named doDecimatedNoFilter

# Build rule for target.
doDecimatedNoFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doDecimatedNoFilter
.PHONY : doDecimatedNoFilter

# fast build rule for target.
doDecimatedNoFilter/fast:
	$(MAKE) -f CMakeFiles/doDecimatedNoFilter.dir/build.make CMakeFiles/doDecimatedNoFilter.dir/build
.PHONY : doDecimatedNoFilter/fast

#=============================================================================
# Target rules for targets named UCorrelator

# Build rule for target.
UCorrelator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UCorrelator
.PHONY : UCorrelator

# fast build rule for target.
UCorrelator/fast:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/build
.PHONY : UCorrelator/fast

#=============================================================================
# Target rules for targets named doWais

# Build rule for target.
doWais: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doWais
.PHONY : doWais

# fast build rule for target.
doWais/fast:
	$(MAKE) -f CMakeFiles/doWais.dir/build.make CMakeFiles/doWais.dir/build
.PHONY : doWais/fast

#=============================================================================
# Target rules for targets named doDecimated

# Build rule for target.
doDecimated: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doDecimated
.PHONY : doDecimated

# fast build rule for target.
doDecimated/fast:
	$(MAKE) -f CMakeFiles/doDecimated.dir/build.make CMakeFiles/doDecimated.dir/build
.PHONY : doDecimated/fast

#=============================================================================
# Target rules for targets named G__UCorrelator.pcm

# Build rule for target.
G__UCorrelator.pcm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 G__UCorrelator.pcm
.PHONY : G__UCorrelator.pcm

# fast build rule for target.
G__UCorrelator.pcm/fast:
	$(MAKE) -f CMakeFiles/G__UCorrelator.pcm.dir/build.make CMakeFiles/G__UCorrelator.pcm.dir/build
.PHONY : G__UCorrelator.pcm/fast

#=============================================================================
# Target rules for targets named evaluateFiltersA3

# Build rule for target.
evaluateFiltersA3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evaluateFiltersA3
.PHONY : evaluateFiltersA3

# fast build rule for target.
evaluateFiltersA3/fast:
	$(MAKE) -f CMakeFiles/evaluateFiltersA3.dir/build.make CMakeFiles/evaluateFiltersA3.dir/build
.PHONY : evaluateFiltersA3/fast

#=============================================================================
# Target rules for targets named doLDB

# Build rule for target.
doLDB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doLDB
.PHONY : doLDB

# fast build rule for target.
doLDB/fast:
	$(MAKE) -f CMakeFiles/doLDB.dir/build.make CMakeFiles/doLDB.dir/build
.PHONY : doLDB/fast

G__UCorrelator.o: G__UCorrelator.cxx.o

.PHONY : G__UCorrelator.o

# target to build an object file
G__UCorrelator.cxx.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/G__UCorrelator.cxx.o
.PHONY : G__UCorrelator.cxx.o

G__UCorrelator.i: G__UCorrelator.cxx.i

.PHONY : G__UCorrelator.i

# target to preprocess a source file
G__UCorrelator.cxx.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/G__UCorrelator.cxx.i
.PHONY : G__UCorrelator.cxx.i

G__UCorrelator.s: G__UCorrelator.cxx.s

.PHONY : G__UCorrelator.s

# target to generate assembly for a file
G__UCorrelator.cxx.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/G__UCorrelator.cxx.s
.PHONY : G__UCorrelator.cxx.s

drivers/doAll.o: drivers/doAll.cc.o

.PHONY : drivers/doAll.o

# target to build an object file
drivers/doAll.cc.o:
	$(MAKE) -f CMakeFiles/doAll.dir/build.make CMakeFiles/doAll.dir/drivers/doAll.cc.o
.PHONY : drivers/doAll.cc.o

drivers/doAll.i: drivers/doAll.cc.i

.PHONY : drivers/doAll.i

# target to preprocess a source file
drivers/doAll.cc.i:
	$(MAKE) -f CMakeFiles/doAll.dir/build.make CMakeFiles/doAll.dir/drivers/doAll.cc.i
.PHONY : drivers/doAll.cc.i

drivers/doAll.s: drivers/doAll.cc.s

.PHONY : drivers/doAll.s

# target to generate assembly for a file
drivers/doAll.cc.s:
	$(MAKE) -f CMakeFiles/doAll.dir/build.make CMakeFiles/doAll.dir/drivers/doAll.cc.s
.PHONY : drivers/doAll.cc.s

drivers/doDecimated.o: drivers/doDecimated.cc.o

.PHONY : drivers/doDecimated.o

# target to build an object file
drivers/doDecimated.cc.o:
	$(MAKE) -f CMakeFiles/doDecimated.dir/build.make CMakeFiles/doDecimated.dir/drivers/doDecimated.cc.o
.PHONY : drivers/doDecimated.cc.o

drivers/doDecimated.i: drivers/doDecimated.cc.i

.PHONY : drivers/doDecimated.i

# target to preprocess a source file
drivers/doDecimated.cc.i:
	$(MAKE) -f CMakeFiles/doDecimated.dir/build.make CMakeFiles/doDecimated.dir/drivers/doDecimated.cc.i
.PHONY : drivers/doDecimated.cc.i

drivers/doDecimated.s: drivers/doDecimated.cc.s

.PHONY : drivers/doDecimated.s

# target to generate assembly for a file
drivers/doDecimated.cc.s:
	$(MAKE) -f CMakeFiles/doDecimated.dir/build.make CMakeFiles/doDecimated.dir/drivers/doDecimated.cc.s
.PHONY : drivers/doDecimated.cc.s

drivers/doDecimatedNoFilter.o: drivers/doDecimatedNoFilter.cc.o

.PHONY : drivers/doDecimatedNoFilter.o

# target to build an object file
drivers/doDecimatedNoFilter.cc.o:
	$(MAKE) -f CMakeFiles/doDecimatedNoFilter.dir/build.make CMakeFiles/doDecimatedNoFilter.dir/drivers/doDecimatedNoFilter.cc.o
.PHONY : drivers/doDecimatedNoFilter.cc.o

drivers/doDecimatedNoFilter.i: drivers/doDecimatedNoFilter.cc.i

.PHONY : drivers/doDecimatedNoFilter.i

# target to preprocess a source file
drivers/doDecimatedNoFilter.cc.i:
	$(MAKE) -f CMakeFiles/doDecimatedNoFilter.dir/build.make CMakeFiles/doDecimatedNoFilter.dir/drivers/doDecimatedNoFilter.cc.i
.PHONY : drivers/doDecimatedNoFilter.cc.i

drivers/doDecimatedNoFilter.s: drivers/doDecimatedNoFilter.cc.s

.PHONY : drivers/doDecimatedNoFilter.s

# target to generate assembly for a file
drivers/doDecimatedNoFilter.cc.s:
	$(MAKE) -f CMakeFiles/doDecimatedNoFilter.dir/build.make CMakeFiles/doDecimatedNoFilter.dir/drivers/doDecimatedNoFilter.cc.s
.PHONY : drivers/doDecimatedNoFilter.cc.s

drivers/doLDB.o: drivers/doLDB.cc.o

.PHONY : drivers/doLDB.o

# target to build an object file
drivers/doLDB.cc.o:
	$(MAKE) -f CMakeFiles/doLDB.dir/build.make CMakeFiles/doLDB.dir/drivers/doLDB.cc.o
.PHONY : drivers/doLDB.cc.o

drivers/doLDB.i: drivers/doLDB.cc.i

.PHONY : drivers/doLDB.i

# target to preprocess a source file
drivers/doLDB.cc.i:
	$(MAKE) -f CMakeFiles/doLDB.dir/build.make CMakeFiles/doLDB.dir/drivers/doLDB.cc.i
.PHONY : drivers/doLDB.cc.i

drivers/doLDB.s: drivers/doLDB.cc.s

.PHONY : drivers/doLDB.s

# target to generate assembly for a file
drivers/doLDB.cc.s:
	$(MAKE) -f CMakeFiles/doLDB.dir/build.make CMakeFiles/doLDB.dir/drivers/doLDB.cc.s
.PHONY : drivers/doLDB.cc.s

drivers/doSimulated.o: drivers/doSimulated.cc.o

.PHONY : drivers/doSimulated.o

# target to build an object file
drivers/doSimulated.cc.o:
	$(MAKE) -f CMakeFiles/doSimulated.dir/build.make CMakeFiles/doSimulated.dir/drivers/doSimulated.cc.o
.PHONY : drivers/doSimulated.cc.o

drivers/doSimulated.i: drivers/doSimulated.cc.i

.PHONY : drivers/doSimulated.i

# target to preprocess a source file
drivers/doSimulated.cc.i:
	$(MAKE) -f CMakeFiles/doSimulated.dir/build.make CMakeFiles/doSimulated.dir/drivers/doSimulated.cc.i
.PHONY : drivers/doSimulated.cc.i

drivers/doSimulated.s: drivers/doSimulated.cc.s

.PHONY : drivers/doSimulated.s

# target to generate assembly for a file
drivers/doSimulated.cc.s:
	$(MAKE) -f CMakeFiles/doSimulated.dir/build.make CMakeFiles/doSimulated.dir/drivers/doSimulated.cc.s
.PHONY : drivers/doSimulated.cc.s

drivers/doWais.o: drivers/doWais.cc.o

.PHONY : drivers/doWais.o

# target to build an object file
drivers/doWais.cc.o:
	$(MAKE) -f CMakeFiles/doWais.dir/build.make CMakeFiles/doWais.dir/drivers/doWais.cc.o
.PHONY : drivers/doWais.cc.o

drivers/doWais.i: drivers/doWais.cc.i

.PHONY : drivers/doWais.i

# target to preprocess a source file
drivers/doWais.cc.i:
	$(MAKE) -f CMakeFiles/doWais.dir/build.make CMakeFiles/doWais.dir/drivers/doWais.cc.i
.PHONY : drivers/doWais.cc.i

drivers/doWais.s: drivers/doWais.cc.s

.PHONY : drivers/doWais.s

# target to generate assembly for a file
drivers/doWais.cc.s:
	$(MAKE) -f CMakeFiles/doWais.dir/build.make CMakeFiles/doWais.dir/drivers/doWais.cc.s
.PHONY : drivers/doWais.cc.s

drivers/evaluateFiltersA3.o: drivers/evaluateFiltersA3.cc.o

.PHONY : drivers/evaluateFiltersA3.o

# target to build an object file
drivers/evaluateFiltersA3.cc.o:
	$(MAKE) -f CMakeFiles/evaluateFiltersA3.dir/build.make CMakeFiles/evaluateFiltersA3.dir/drivers/evaluateFiltersA3.cc.o
.PHONY : drivers/evaluateFiltersA3.cc.o

drivers/evaluateFiltersA3.i: drivers/evaluateFiltersA3.cc.i

.PHONY : drivers/evaluateFiltersA3.i

# target to preprocess a source file
drivers/evaluateFiltersA3.cc.i:
	$(MAKE) -f CMakeFiles/evaluateFiltersA3.dir/build.make CMakeFiles/evaluateFiltersA3.dir/drivers/evaluateFiltersA3.cc.i
.PHONY : drivers/evaluateFiltersA3.cc.i

drivers/evaluateFiltersA3.s: drivers/evaluateFiltersA3.cc.s

.PHONY : drivers/evaluateFiltersA3.s

# target to generate assembly for a file
drivers/evaluateFiltersA3.cc.s:
	$(MAKE) -f CMakeFiles/evaluateFiltersA3.dir/build.make CMakeFiles/evaluateFiltersA3.dir/drivers/evaluateFiltersA3.cc.s
.PHONY : drivers/evaluateFiltersA3.cc.s

src/AnalysisConfig.o: src/AnalysisConfig.cc.o

.PHONY : src/AnalysisConfig.o

# target to build an object file
src/AnalysisConfig.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/AnalysisConfig.cc.o
.PHONY : src/AnalysisConfig.cc.o

src/AnalysisConfig.i: src/AnalysisConfig.cc.i

.PHONY : src/AnalysisConfig.i

# target to preprocess a source file
src/AnalysisConfig.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/AnalysisConfig.cc.i
.PHONY : src/AnalysisConfig.cc.i

src/AnalysisConfig.s: src/AnalysisConfig.cc.s

.PHONY : src/AnalysisConfig.s

# target to generate assembly for a file
src/AnalysisConfig.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/AnalysisConfig.cc.s
.PHONY : src/AnalysisConfig.cc.s

src/Analyzer.o: src/Analyzer.cc.o

.PHONY : src/Analyzer.o

# target to build an object file
src/Analyzer.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Analyzer.cc.o
.PHONY : src/Analyzer.cc.o

src/Analyzer.i: src/Analyzer.cc.i

.PHONY : src/Analyzer.i

# target to preprocess a source file
src/Analyzer.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Analyzer.cc.i
.PHONY : src/Analyzer.cc.i

src/Analyzer.s: src/Analyzer.cc.s

.PHONY : src/Analyzer.s

# target to generate assembly for a file
src/Analyzer.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Analyzer.cc.s
.PHONY : src/Analyzer.cc.s

src/AntennaPositions.o: src/AntennaPositions.cc.o

.PHONY : src/AntennaPositions.o

# target to build an object file
src/AntennaPositions.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/AntennaPositions.cc.o
.PHONY : src/AntennaPositions.cc.o

src/AntennaPositions.i: src/AntennaPositions.cc.i

.PHONY : src/AntennaPositions.i

# target to preprocess a source file
src/AntennaPositions.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/AntennaPositions.cc.i
.PHONY : src/AntennaPositions.cc.i

src/AntennaPositions.s: src/AntennaPositions.cc.s

.PHONY : src/AntennaPositions.s

# target to generate assembly for a file
src/AntennaPositions.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/AntennaPositions.cc.s
.PHONY : src/AntennaPositions.cc.s

src/Baseline.o: src/Baseline.cc.o

.PHONY : src/Baseline.o

# target to build an object file
src/Baseline.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Baseline.cc.o
.PHONY : src/Baseline.cc.o

src/Baseline.i: src/Baseline.cc.i

.PHONY : src/Baseline.i

# target to preprocess a source file
src/Baseline.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Baseline.cc.i
.PHONY : src/Baseline.cc.i

src/Baseline.s: src/Baseline.cc.s

.PHONY : src/Baseline.s

# target to generate assembly for a file
src/Baseline.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Baseline.cc.s
.PHONY : src/Baseline.cc.s

src/Correlator.o: src/Correlator.cc.o

.PHONY : src/Correlator.o

# target to build an object file
src/Correlator.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Correlator.cc.o
.PHONY : src/Correlator.cc.o

src/Correlator.i: src/Correlator.cc.i

.PHONY : src/Correlator.i

# target to preprocess a source file
src/Correlator.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Correlator.cc.i
.PHONY : src/Correlator.cc.i

src/Correlator.s: src/Correlator.cc.s

.PHONY : src/Correlator.s

# target to generate assembly for a file
src/Correlator.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Correlator.cc.s
.PHONY : src/Correlator.cc.s

src/Flags.o: src/Flags.cc.o

.PHONY : src/Flags.o

# target to build an object file
src/Flags.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Flags.cc.o
.PHONY : src/Flags.cc.o

src/Flags.i: src/Flags.cc.i

.PHONY : src/Flags.i

# target to preprocess a source file
src/Flags.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Flags.cc.i
.PHONY : src/Flags.cc.i

src/Flags.s: src/Flags.cc.s

.PHONY : src/Flags.s

# target to generate assembly for a file
src/Flags.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Flags.cc.s
.PHONY : src/Flags.cc.s

src/ImageTools.o: src/ImageTools.cc.o

.PHONY : src/ImageTools.o

# target to build an object file
src/ImageTools.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ImageTools.cc.o
.PHONY : src/ImageTools.cc.o

src/ImageTools.i: src/ImageTools.cc.i

.PHONY : src/ImageTools.i

# target to preprocess a source file
src/ImageTools.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ImageTools.cc.i
.PHONY : src/ImageTools.cc.i

src/ImageTools.s: src/ImageTools.cc.s

.PHONY : src/ImageTools.s

# target to generate assembly for a file
src/ImageTools.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ImageTools.cc.s
.PHONY : src/ImageTools.cc.s

src/PeakFinder.o: src/PeakFinder.cc.o

.PHONY : src/PeakFinder.o

# target to build an object file
src/PeakFinder.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/PeakFinder.cc.o
.PHONY : src/PeakFinder.cc.o

src/PeakFinder.i: src/PeakFinder.cc.i

.PHONY : src/PeakFinder.i

# target to preprocess a source file
src/PeakFinder.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/PeakFinder.cc.i
.PHONY : src/PeakFinder.cc.i

src/PeakFinder.s: src/PeakFinder.cc.s

.PHONY : src/PeakFinder.s

# target to generate assembly for a file
src/PeakFinder.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/PeakFinder.cc.s
.PHONY : src/PeakFinder.cc.s

src/ResponseManager.o: src/ResponseManager.cc.o

.PHONY : src/ResponseManager.o

# target to build an object file
src/ResponseManager.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ResponseManager.cc.o
.PHONY : src/ResponseManager.cc.o

src/ResponseManager.i: src/ResponseManager.cc.i

.PHONY : src/ResponseManager.i

# target to preprocess a source file
src/ResponseManager.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ResponseManager.cc.i
.PHONY : src/ResponseManager.cc.i

src/ResponseManager.s: src/ResponseManager.cc.s

.PHONY : src/ResponseManager.s

# target to generate assembly for a file
src/ResponseManager.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ResponseManager.cc.s
.PHONY : src/ResponseManager.cc.s

src/ShapeParameters.o: src/ShapeParameters.cc.o

.PHONY : src/ShapeParameters.o

# target to build an object file
src/ShapeParameters.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ShapeParameters.cc.o
.PHONY : src/ShapeParameters.cc.o

src/ShapeParameters.i: src/ShapeParameters.cc.i

.PHONY : src/ShapeParameters.i

# target to preprocess a source file
src/ShapeParameters.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ShapeParameters.cc.i
.PHONY : src/ShapeParameters.cc.i

src/ShapeParameters.s: src/ShapeParameters.cc.s

.PHONY : src/ShapeParameters.s

# target to generate assembly for a file
src/ShapeParameters.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/ShapeParameters.cc.s
.PHONY : src/ShapeParameters.cc.s

src/SpectrumAverage.o: src/SpectrumAverage.cc.o

.PHONY : src/SpectrumAverage.o

# target to build an object file
src/SpectrumAverage.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SpectrumAverage.cc.o
.PHONY : src/SpectrumAverage.cc.o

src/SpectrumAverage.i: src/SpectrumAverage.cc.i

.PHONY : src/SpectrumAverage.i

# target to preprocess a source file
src/SpectrumAverage.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SpectrumAverage.cc.i
.PHONY : src/SpectrumAverage.cc.i

src/SpectrumAverage.s: src/SpectrumAverage.cc.s

.PHONY : src/SpectrumAverage.s

# target to generate assembly for a file
src/SpectrumAverage.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SpectrumAverage.cc.s
.PHONY : src/SpectrumAverage.cc.s

src/SpectrumParameters.o: src/SpectrumParameters.cc.o

.PHONY : src/SpectrumParameters.o

# target to build an object file
src/SpectrumParameters.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SpectrumParameters.cc.o
.PHONY : src/SpectrumParameters.cc.o

src/SpectrumParameters.i: src/SpectrumParameters.cc.i

.PHONY : src/SpectrumParameters.i

# target to preprocess a source file
src/SpectrumParameters.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SpectrumParameters.cc.i
.PHONY : src/SpectrumParameters.cc.i

src/SpectrumParameters.s: src/SpectrumParameters.cc.s

.PHONY : src/SpectrumParameters.s

# target to generate assembly for a file
src/SpectrumParameters.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SpectrumParameters.cc.s
.PHONY : src/SpectrumParameters.cc.s

src/SystemResponse.o: src/SystemResponse.cc.o

.PHONY : src/SystemResponse.o

# target to build an object file
src/SystemResponse.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SystemResponse.cc.o
.PHONY : src/SystemResponse.cc.o

src/SystemResponse.i: src/SystemResponse.cc.i

.PHONY : src/SystemResponse.i

# target to preprocess a source file
src/SystemResponse.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SystemResponse.cc.i
.PHONY : src/SystemResponse.cc.i

src/SystemResponse.s: src/SystemResponse.cc.s

.PHONY : src/SystemResponse.s

# target to generate assembly for a file
src/SystemResponse.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/SystemResponse.cc.s
.PHONY : src/SystemResponse.cc.s

src/UCFilters.o: src/UCFilters.cc.o

.PHONY : src/UCFilters.o

# target to build an object file
src/UCFilters.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/UCFilters.cc.o
.PHONY : src/UCFilters.cc.o

src/UCFilters.i: src/UCFilters.cc.i

.PHONY : src/UCFilters.i

# target to preprocess a source file
src/UCFilters.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/UCFilters.cc.i
.PHONY : src/UCFilters.cc.i

src/UCFilters.s: src/UCFilters.cc.s

.PHONY : src/UCFilters.s

# target to generate assembly for a file
src/UCFilters.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/UCFilters.cc.s
.PHONY : src/UCFilters.cc.s

src/Util.o: src/Util.cc.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Util.cc.o
.PHONY : src/Util.cc.o

src/Util.i: src/Util.cc.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Util.cc.i
.PHONY : src/Util.cc.i

src/Util.s: src/Util.cc.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/Util.cc.s
.PHONY : src/Util.cc.s

src/WaveformCombiner.o: src/WaveformCombiner.cc.o

.PHONY : src/WaveformCombiner.o

# target to build an object file
src/WaveformCombiner.cc.o:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/WaveformCombiner.cc.o
.PHONY : src/WaveformCombiner.cc.o

src/WaveformCombiner.i: src/WaveformCombiner.cc.i

.PHONY : src/WaveformCombiner.i

# target to preprocess a source file
src/WaveformCombiner.cc.i:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/WaveformCombiner.cc.i
.PHONY : src/WaveformCombiner.cc.i

src/WaveformCombiner.s: src/WaveformCombiner.cc.s

.PHONY : src/WaveformCombiner.s

# target to generate assembly for a file
src/WaveformCombiner.cc.s:
	$(MAKE) -f CMakeFiles/UCorrelator.dir/build.make CMakeFiles/UCorrelator.dir/src/WaveformCombiner.cc.s
.PHONY : src/WaveformCombiner.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... doAll"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... doSimulated"
	@echo "... doDecimatedNoFilter"
	@echo "... UCorrelator"
	@echo "... doWais"
	@echo "... doDecimated"
	@echo "... G__UCorrelator.pcm"
	@echo "... evaluateFiltersA3"
	@echo "... install/strip"
	@echo "... doLDB"
	@echo "... G__UCorrelator.o"
	@echo "... G__UCorrelator.i"
	@echo "... G__UCorrelator.s"
	@echo "... drivers/doAll.o"
	@echo "... drivers/doAll.i"
	@echo "... drivers/doAll.s"
	@echo "... drivers/doDecimated.o"
	@echo "... drivers/doDecimated.i"
	@echo "... drivers/doDecimated.s"
	@echo "... drivers/doDecimatedNoFilter.o"
	@echo "... drivers/doDecimatedNoFilter.i"
	@echo "... drivers/doDecimatedNoFilter.s"
	@echo "... drivers/doLDB.o"
	@echo "... drivers/doLDB.i"
	@echo "... drivers/doLDB.s"
	@echo "... drivers/doSimulated.o"
	@echo "... drivers/doSimulated.i"
	@echo "... drivers/doSimulated.s"
	@echo "... drivers/doWais.o"
	@echo "... drivers/doWais.i"
	@echo "... drivers/doWais.s"
	@echo "... drivers/evaluateFiltersA3.o"
	@echo "... drivers/evaluateFiltersA3.i"
	@echo "... drivers/evaluateFiltersA3.s"
	@echo "... src/AnalysisConfig.o"
	@echo "... src/AnalysisConfig.i"
	@echo "... src/AnalysisConfig.s"
	@echo "... src/Analyzer.o"
	@echo "... src/Analyzer.i"
	@echo "... src/Analyzer.s"
	@echo "... src/AntennaPositions.o"
	@echo "... src/AntennaPositions.i"
	@echo "... src/AntennaPositions.s"
	@echo "... src/Baseline.o"
	@echo "... src/Baseline.i"
	@echo "... src/Baseline.s"
	@echo "... src/Correlator.o"
	@echo "... src/Correlator.i"
	@echo "... src/Correlator.s"
	@echo "... src/Flags.o"
	@echo "... src/Flags.i"
	@echo "... src/Flags.s"
	@echo "... src/ImageTools.o"
	@echo "... src/ImageTools.i"
	@echo "... src/ImageTools.s"
	@echo "... src/PeakFinder.o"
	@echo "... src/PeakFinder.i"
	@echo "... src/PeakFinder.s"
	@echo "... src/ResponseManager.o"
	@echo "... src/ResponseManager.i"
	@echo "... src/ResponseManager.s"
	@echo "... src/ShapeParameters.o"
	@echo "... src/ShapeParameters.i"
	@echo "... src/ShapeParameters.s"
	@echo "... src/SpectrumAverage.o"
	@echo "... src/SpectrumAverage.i"
	@echo "... src/SpectrumAverage.s"
	@echo "... src/SpectrumParameters.o"
	@echo "... src/SpectrumParameters.i"
	@echo "... src/SpectrumParameters.s"
	@echo "... src/SystemResponse.o"
	@echo "... src/SystemResponse.i"
	@echo "... src/SystemResponse.s"
	@echo "... src/UCFilters.o"
	@echo "... src/UCFilters.i"
	@echo "... src/UCFilters.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/WaveformCombiner.o"
	@echo "... src/WaveformCombiner.i"
	@echo "... src/WaveformCombiner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

