### Separated out configuration options  #### 

###### Begin Compilation Options #######

### Override the compiler here (might be helpful on older Macs or testing with multiple compilers) 
#CXX=clang++



#modify optimization flags here
CXXFLAGS += -march=native 
LDFLAGS += 


# Force old ABI for g++ 5+ and ROOT 6 
CXXFLAGS +=-D_GLIBCXX_USE_CXX11_ABI=0 

# Enable multithread support
CXXFLAGS += -DUCORRELATOR_OPENMP -fopenmp
LDFLAGS += -fopenmp

#if FFTtools was compiled with OpenMP support, you can uncomment the following line 
# to allow parallel evaluation of FFT's. Otherwise, it will only do one FFT at a time. 
CXXFLAGS += -DFFTTOOLS_COMPILED_WITH_OPENMP


#####Site Specific  Flags (adjust to local site)
DLLSUF = ${DllSuf}
OBJSUF = ${ObjSuf}

ifndef ANITA_UTIL_INSTALL_DIR
ANITA_UTIL_INSTALL_DIR=/usr/local/ 
endif


