# This module defines

# LIBCONFIG_INCLUDE_DIR
# LIBCONFIG_LIBRARIES
# LIBCONFIG_FOUND

MESSAGE("Searching for libconfig library")

FIND_PATH(LIBCONFIG_INCLUDE_DIR libconfig.h
  /usr/local/include
  /usr/include
  $ENV{CPATH}
)

FIND_PATH(LIBCONFIGPP_INCLUDE_DIR libconfig.h++
  /usr/local/include
  /usr/include
  $ENV{CPATH}
)

FIND_LIBRARY(LIBCONFIG_LIBRARY config
  /usr/local/lib
  /usr/lib
  $ENV{LIBRARY_PATH}
  $ENV{LD_LIBRARY_PATH}
  $ENV{DYLD_LIBRARY_PATH}
)

FIND_LIBRARY(LIBCONFIGPP_LIBRARY config++
  /usr/local/lib
  /usr/lib
  $ENV{LIBRARY_PATH}
  $ENV{LD_LIBRARY_PATH}
  $ENV{DYLD_LIBRARY_PATH}
)


IF(LIBCONFIG_INCLUDE_DIR)
  IF(LIBCONFIG_LIBRARY)
    SET(LIBCONFIG_FOUND TRUE)
    SET(LIBCONFIG_LIBRARIES ${LIBCONFIG_LIBRARY})
    SET(LIBCONFIG_EXE_LINKER_FLAGS -lconfig ) 
  ENDIF(LIBCONFIG_LIBRARY)
ENDIF(LIBCONFIG_INCLUDE_DIR)

IF(LIBCONFIGPP_INCLUDE_DIR)
  IF(LIBCONFIGPP_LIBRARY)
    SET(LIBCONFIGPP_FOUND TRUE)
    SET(LIBCONFIGPP_LIBRARIES ${LIBCONFIGPP_LIBRARY})
    SET(LIBCONFIG_EXE_LINKER_FLAGS -lconfig++ ) 
  ENDIF(LIBCONFIGPP_LIBRARY)
ENDIF(LIBCONFIGPP_INCLUDE_DIR)

IF (LIBCONFIG_FOUND)
   MESSAGE("Found LibConfig++: ${LIBCONFIGPP_LIBRARIES}" )
   MESSAGE("Found LibConfig: ${LIBCONFIG_LIBRARIES}")
ELSE (LIBCONFIG_FOUND)
   IF (LibConfig_FIND_REQUIRED)
      MESSAGE(SEND_ERROR "Could NOT find LibConfig")
   ENDIF (LibConfig_FIND_REQUIRED)
ENDIF (LIBCONFIG_FOUND)

MARK_AS_ADVANCED(LIBCONFIG_INCLUDE_DIR LIBCONFIG_LIBRARIES LIBCONFIG_LIBRARY LIBCONFIGPP_LIBRARY LIBCONFIGPP_INCLUDE_DIR)

